### ISSUE TITLE
Provide an easy way to synchronize vostok and microsoft environment names

### ISSUE THREAD

**Issue by KungA** [vostok/applications.aspnetcore#15]
https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#set-the-environment

**Comment by iloktionov** [comment]
Nothing to do here, there's already an easy way:
```
builder.SetupWebHost(b => b.UseEnvironment(vostok.ApplicationIdentity.Environment));
```
