### ISSUE TITLE
InvalidOperationException has occurred when application starting up

### ISSUE THREAD

**Issue by ArXa1L** [vostok/applications.aspnetcore#6]
Hi, 
I created a new ASPNET.Core application using the "empty" template. After that, I added the minimum necessary code to run my application:

```cs
using System.Threading.Tasks;
using Vostok.Applications.AspNetCore;
using Vostok.Hosting;
using Vostok.Hosting.Setup;

namespace ExampleApp
{
    public sealed class App : VostokAspNetCoreApplication<Startup>
    {
        public static Task Main(string[] args)
        {
            var application = new App();
            var hostSettings = new VostokHostSettings(application, application.ConfigureEnvironment);
            return new VostokHost(hostSettings).WithConsoleCancellation().RunAsync();
        }

        private void ConfigureEnvironment(IVostokHostingEnvironmentBuilder builder)
        {
            builder.SetupApplicationIdentity(ConfigureIdentity);
            builder.SetupLog(ConfigureLogging);
            builder.SetPort(1234);
        }

        private void ConfigureIdentity(IVostokApplicationIdentityBuilder identityBuilder)
        {
            identityBuilder.SetProject("MyProject");
            identityBuilder.SetApplication("MyApplication");
            identityBuilder.SetInstance("instance");
            identityBuilder.SetEnvironment("environment");
        }

        private void ConfigureLogging(IVostokCompositeLogBuilder logBuilder)
        {
            logBuilder.SetupConsoleLog();
        }
    }
}

```

When I launched the application, it immediately crashed, and there was the following error in the log:
```
2020-03-03 11: 17: 30,733 FATAL [Microsoft.AspNetCore.Hosting.Diagnostics] Application startup exception
System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddRouting' inside the call to 'ConfigureServices (...)' in the application startup code.
```

**Comment by KungA** [comment]
Seems just your Startup class incorrect.
Does it works before you wrap it into VostokAspNetCoreApplication?

**Comment by ArXa1L** [comment]
Yep, you can reproduce the problem if you create a new project using `dotnet new web -n ExampleApp` command

**Comment by iloktionov** [comment]
Found the culprit. Turns out we're using `ConfigureWeHost(..)` instead of `ConfigureWebHostDefaults()` in the template. I'm going to whip up a fix for this problem today.

For the time being, a simple `services.AddRouting();` line in `ConfigureServices()` takes care of this.

**Comment by iloktionov** [comment]
Fixed this in https://github.com/vostok/applications.aspnetcore/commit/542cee03a8f64fc9adb0b71f8e9c8170ca358d0e.

We're currently unsure whether it's optimal to use `ConfigureWebHostDefaults()` due to not-so-desired IIS integration, so the fix is fairly straightforward. Using all of the defaults could be discussed separately.
